import type { Metadata } from "next";
import "./index.css";
import Navbar from "@/components/Navbar";
import { CartProvider } from "@/context/CartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <link rel="icon" href="favicon.svg" type="image/svg+xml" />
        <CartProvider>
          <header className="flex relative top-0 bg-[#191919] z-[20] w-full gap-4 justify-between items-center sm:px-20 lg:px-40 md:pt-[1.8rem] p-6 border-b border-gray-100 border-opacity-10">
            <Navbar />
          </header>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
